export const GET_BEER_LIST_BY_NAME_STARTED = 'GET_BEER_LIST_BY_NAME_STARTED';
export const GET_BEER_LIST_BY_NAME_SUCCESS = 'GET_BEER_LIST_BY_NAME_SUCCESS';
export const GET_BEER_LIST_BY_NAME_FAILURE = 'GET_BEER_LIST_BY_NAME_FAILURE';

export const GET_TOP_TEN_BY_ABV_STARTED = 'GET_TOP_TEN_BY_ABV_STARTED';
export const GET_TOP_TEN_BY_ABV_SUCCESS = 'GET_TOP_TEN_BY_ABV_SUCCESS';
export const GET_TOP_TEN_BY_ABV_FAILURE = 'GET_TOP_TEN_BY_ABV_FAILURE';

export const GET_TOP_TEN_OLDEST_STARTED = 'GET_TOP_TEN_OLDEST_STARTED';
export const GET_TOP_TEN_OLDEST_SUCCESS = 'GET_TOP_TEN_OLDEST_SUCCESS';
export const GET_TOP_TEN_OLDEST_FAILURE = 'GET_TOP_TEN_OLDEST_FAILURE';

export const GET_TOP_TEN_NEWEST_STARTED = 'GET_TOP_TEN_NEWEST_STARTED';
export const GET_TOP_TEN_NEWEST_SUCCESS = 'GET_TOP_TEN_NEWEST_SUCCESS';
export const GET_TOP_TEN_NEWEST_FAILURE = 'GET_TOP_TEN_NEWEST_FAILURE';

export const GET_RANDOM_BEER_LIST_STARTED = 'GET_RANDOM_BEER_LIST_STARTED';
export const GET_RANDOM_BEER_LIST_SUCCESS = 'GET_RANDOM_BEER_LIST_SUCCESS';
export const GET_RANDOM_BEER_LIST_FAILURE = 'GET_RANDOM_BEER_LIST_FAILURE';

export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE';
export const NAVIGATE_TO_FAVOURITES = 'NAVIGATE_TO_FAVOURITES';


