version: 2

defaults: &defaults
    docker:
        - image: circleci/node:9.8
    working_directory: ~/tmp

jobs:
    setup:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                  root: ~/tmp
                  paths:
                      - src
                      - node_modules
                      - package.json
                      - .circleci
                      - build
                      - public

    test:
        setup:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/tmp
            - run: npm test
            - run:
                  command: npm start
                  background: true

    deploy:
        setup:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/tmp
            - run: npm run build
            - add_ssh_keys:
            - run: scp -oStrictHostKeyChecking=no -r ~/tmp/build/* ${REMOTE_USER}@${DEPLOY_HOST}:${REMOTE_FOLDER}

workflows:
    version: 2
    setup-test-deploy:
        jobs:
            - setup
            - test:
                  requires:
                      - setup
            - deploy:
                  requires:
                      - setup
                      - test
                  filters:
                      branches:
                          only:
                              - master
